### ISSUE TITLE
Some examples from openhab2-jython/Script Examples/hello_world.py don't work

### ISSUE THREAD

**Issue by ricadelic** [OH-Jython-Scripters/openhab2-jython#96]
**Describe the bug**
Some examples on the page openhab2-jython/Script Examples/hello_world.py don't work.

**To Reproduce**
1. Use Openhab 2.4, Jython 2.7.0 standalone in a docker environment
2. Follow the instructions on the wiki to enable Jython support
3. Run the hello_world.py examples
4. Error 1

**- RawAPICron**
Error: 

> 10-May-2019 22:30:02.680 [ERROR] [ion.module.script.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/personal/in_test/hello_world.py': TypeError: can't convert ['Test tag'] to java.util.Set in <script> at line number 24

5. Error 2:
self.log.info("message") doesn't work for
- RawAPICron
- RawAPIStateUpdate
- ExtensionCron
- ExtensionItemUpdate

**Expected behavior**
The self.log.info works.

When using the @rule decorator, the problem isn't there.

**Environment (please complete the following information):**
 - Jython version: [e.g. 2.7.0 standalone,]
 - openHAB version: [e.g. 2.4.0 release build]
 - Release: latest master (downloaded 10-05-2019, around 22:00 amsterdam time)

**Additional context**
Log entry:

> 10-May-2019 22:40:00.005 [DEBUG] [.smarthome.automation.core.internal.RuleEngineImpl] - The trigger 'Hello_World_Cron_Trigger' of rule '10b8239a-dcd8-4772-9ca9-a5dcb6637784' is triggered.
10-May-2019 22:40:00.008 [ERROR] [.smarthome.automation.core.internal.RuleEngineImpl] - Failed to execute rule '10b8239a-dcd8-4772-9ca9-a5dcb6637784': Fail to execute action: 1
10-May-2019 22:40:00.010 [DEBUG] [.smarthome.automation.core.internal.RuleEngineImpl] -
java.lang.RuntimeException: Fail to execute action: 1
        at org.eclipse.smarthome.automation.core.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1207) ~[205:org.eclipse.smarthome.automation.core:0.10.0.oh240]
        at org.eclipse.smarthome.automation.core.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:1004) [205:org.eclipse.smarthome.automation.core:0.10.0.oh240]
        at org.eclipse.smarthome.automation.core.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:91) [205:org.eclipse.smarthome.automation.core:0.10.0.oh240]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: org.python.core.PyException
        at org.python.core.Py.AttributeError(Py.java:205) ~[?:?]
        at org.python.core.PyObject.noAttributeError(PyObject.java:1013) ~[?:?]
        at org.python.core.PyObject.__getattr__(PyObject.java:1008) ~[?:?]
        at org.python.pycode._pyx50.execute$3(<script>:23) ~[?:?]
        at org.python.pycode._pyx50.call_function(<script>) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:167) ~[?:?]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307) ~[?:?]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198) ~[?:?]
        at org.python.core.PyFunction.__call__(PyFunction.java:482) ~[?:?]
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[?:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[?:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[?:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:213) ~[?:?]
        at org.python.core.PyObject._jcallexc(PyObject.java:3626) ~[?:?]
        at org.python.core.PyObject._jcall(PyObject.java:3658) ~[?:?]
        at org.python.proxies.__builtin__$RawAPICron$55.execute(Unknown Source) ~[?:?]
        at org.eclipse.smarthome.automation.module.script.rulesupport.shared.simple.SimpleRuleActionHandlerDelegate.execute(SimpleRuleActionHandlerDelegate.java:34) ~[?:?]
        at org.eclipse.smarthome.automation.module.script.rulesupport.internal.delegates.SimpleActionHandlerDelegate.execute(SimpleActionHandlerDelegate.java:60) ~[?:?]
        at org.eclipse.smarthome.automation.core.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1199) ~[?:?]
        ... 7 more

**Comment by ricadelic** [comment]
I'm not a good Python programmer, but it seems to me that when using rule  self is extended with the log.info class and when using the SimpleRule definition, another import needs to be done?

**Comment by openhab-5iver** [comment]
Thank you... try out the latest!

**Comment by ricadelic** [comment]
I will. Cheers!
